### ISSUE TITLE
feat picture

### ISSUE THREAD

**Issue by j314h** [maxime841/Second-life-API#142]
## create 

- [x] Modifier model, migration, factory, seed

## feat

- [x]  #150 update => modifier une image staff (user root)
- [x]  #150 delete => supprimer une image staff (user root)

- [x]  #147 update => modifier une image land (user Admin)
- [x]  #147 delete => supprimer une image land (user Admin)
- [x]  #147 update => modifier une image house (user Admin)
- [x]  #147 delete => supprimer une image house (user Admin)

- [x] update => modifier une image club (user Manager club)
- [x] delete => supprimer une image club (user Manager club)

- [x] update => modifier une image dj (user Manager dj / user Manager dancer)
- [x] delete => supprimer une image dj / dancer (user Manager dj / user Manager dancer)

- [x] updarte favori picture
